# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be2b86e641c83d28504f554dde106c4946c2ae1820d034908215ae34f31d5e51066513dd2510eec8ed25a17c0f403564f12f88300fa871c95397370aa6a2964a
  olx_url: "https://www.olx.pl/nieruchomosci/mieszkania/wynajem/sopot/?search%5Bfilter_float_price%3Afrom%5D=800&search%5Bfilter_float_price%3Ato%5D=1600&search%5Bfilter_enum_rooms%5D%5B0%5D=two&search%5Bdist%5D=15"
  trojmiasto_url: "http://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/wi,100,ai,800_1600,e1i,81_37_32_1_87_76_2_7_31_29_60_26_93_82_22_23_4_84,ri,2_2.html"

test:
  secret_key_base: 1eb70674cafb82c1d3b729b6cd9386f1b817ca5103f3e20886373f9212b4cab5cf3e47e877f1fbfbdd0a1ac16a32c5fc6749c249fa92f7f08c7f33ccaee36762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  olx_url: "https://www.olx.pl/nieruchomosci/mieszkania/wynajem/sopot/?search%5Bfilter_float_price%3Afrom%5D=800&search%5Bfilter_float_price%3Ato%5D=1600&search%5Bfilter_enum_rooms%5D%5B0%5D=two&search%5Bdist%5D=15"
  trojmiasto_url: "http://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/wi,100,ai,800_1600,e1i,81_37_32_1_87_76_2_7_31_29_60_26_93_82_22_23_4_84,ri,2_2.html"
